version: "3.9"

services:
  test:
    build: .
    command: pytest tests/ -v --cov=pymast --cov-report=term-missing
    volumes:
      - .:/app

  jupyter:
    build: .
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - .:/app
